### ISSUE TITLE
Delay purchases until after server tick update

### ISSUE THREAD

**Issue by jnsnow** [DannyDaemonic/SteamMonsterAutoUpgradeManager#1]
Purchases should be delayed until after a server tick instead of relying on the local numbers, because it will produce false information for the optimum upgrade path, and then the upgrade gets rolled back on you.

**Comment by DannyDaemonic** [comment]
I think there's always at least one tick between purchases. Could you give me an example when it does multiple purchases at once and they have to be rolled back?

**Comment by jnsnow** [comment]
It's not when it does multiple at once, it's more that sometimes after a
Raining Gold round, the gold will inch up juuust high enough to afford
something like BF19, but then the server will update and roll us back ever
so slightly below the requisite amount. When this happens, the script will
sometimes purchase what it thought was the next best thing, like LS or
Elemental damage, which leaves us unable to purchase BH for the next long
while.

I tend to be pretty active at my console casting 'extra' spells, usually
Treasure!, Steal Health and Reflect Damage, so I suspect I am triggering a
"too many actions per second" error sometimes, which can fool the
auto-purchase script.

**Comment by jnsnow** [comment]
Game doesn't exist anymore, so closing issue (:
