### ISSUE TITLE
New calculation to determine elemental upgrades

### ISSUE THREAD

**Issue by inter5tella** [DannyDaemonic/SteamMonsterAutoUpgradeManager#2]
The way to determine which element you have to upgrade to max. the teamDPS has changed:

(parseInt(w.g_steamID.slice(-2)) + (parseInt(w.g_Minigame.gameid) % 100)) % 4

Was upgrading water element and after activating the script, it upgrades fire all the time.

**Comment by DannyDaemonic** [comment]
Hey, that's my code. Updated.

**Comment by inter5tella** [comment]
Just found it on the Steamgroup Strategy Guide and after the script was buying my not preferred element i thought your script still calculates from the steamID mod.

But thx anymway for the update <3
